on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: rustup install stable --profile minimal
      - uses: actions/checkout@v4
      - run: cargo generate-lockfile
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ !inputs.release }}
        run: cargo build
      - if: ${{ inputs.release }}
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: target/*/*.exe
